name 'gocd-agent'
maintainer 'Steven Wade'
maintainer_email 'wades@parliament.uk'
license 'all_rights'
description 'Installs/Configures template'
long_description 'Installs/Configures template'
version '0.1.7'
depends 'gocd'
depends 'powershell'
depends 'chocolatey'
