---
driver:
  name: docker
  privileged: true

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: centos-6.4
# - name: centos-7
- name: ubuntu-12.04
  driver:
    provision_command:
      - "apt-get install -y net-tools" # netstat, needed to run specs
      - "apt-get install -y libfuse2"
      - "mkdir -p /tmp/fuse"
      - "cd /tmp/fuse ; apt-get download fuse"
      - "cd /tmp/fuse ; dpkg-deb -x fuse_* ."
      - "cd /tmp/fuse ; dpkg-deb -e fuse_*"
      - "cd /tmp/fuse ; rm fuse_*.deb"
      - "cd /tmp/fuse ; echo '#!/bin/bash\\nexit 0\\n' > DEBIAN/postinst"
      - "cd /tmp/fuse ; cat DEBIAN/postinst"
      - "cd /tmp/fuse ; dpkg-deb -b . /tmp/fuse.deb"
      - "cd /tmp/fuse ; dpkg -i /tmp/fuse.deb"
- name: ubuntu-14.04
  driver:
    provision_command:
      - "apt-get install -y net-tools" # netstat, needed to run specs
      - "apt-get install -y libfuse2"
      - "mkdir -p /tmp/fuse"
      - "cd /tmp/fuse ; apt-get download fuse"
      - "cd /tmp/fuse ; dpkg-deb -x fuse_* ."
      - "cd /tmp/fuse ; dpkg-deb -e fuse_*"
      - "cd /tmp/fuse ; rm fuse_*.deb"
      - "cd /tmp/fuse ; echo '#!/bin/bash\\nexit 0\\n' > DEBIAN/postinst"
      - "cd /tmp/fuse ; cat DEBIAN/postinst"
      - "cd /tmp/fuse ; dpkg-deb -b . /tmp/fuse.deb"
      - "cd /tmp/fuse ; dpkg -i /tmp/fuse.deb"

suites:
- name: default
  run_list:
  - recipe[gocd]
  attributes:
    gocd:
      server:
        max_mem: '1024m'
        min_mem: '512m'
      agent:
        count: 2 # good test for agent lwrp
        autoregister:
          key: 'auto-register-key'
          environments: ['staging', 'perf']
          resources: ['foo', 'bar', 'baz']
          hostname: 'example-host'
- name: package_file
  run_list:
  - recipe[gocd]
  attributes:
    gocd:
      install_method: 'package_file'
      server:
        max_mem: '1024m'
        min_mem: '512m'
      agent:
        autoregister:
          key: 'auto-register-key'
          environments: ['staging', 'perf']
          resources: ['foo', 'bar', 'baz']
          hostname: 'example-host'
